### ISSUE TITLE
SSH unable to run

### ISSUE THREAD

**Issue by seb26** [OneCDOnly/create-autorun#16]
Sadly I can't get openssh to run, even though it is specified in a script in autorun/scripts.

QNAP TS-431P:
```
[~] # uname -a
Linux NAS31D3FC 4.2.8 #2 SMP Tue Nov 28 05:34:53 CST 2023 armv7l unknown
```

I have installed Entware_1.03a_std.qpkg from [Entware](https://github.com/Entware/Entware), and installed openssh-server.

I run create-autorun:
```
[~] # curl -skL https://git.io/create-autorun | sudo bash
create-autorun.sh 230527

info: NAS model: TS-431P 
info: QTS version: 5.1.4 #20231128 
info: default volume: /share/CACHEDEV1_DATA 
info: autorun partition should be: /dev/mtd6 
done: ubiattached partition: 6 
done: mounted: ubifs device: ubi2:config -> /tmp/create-autorun.S1odE3 
info: confirmed partition tag-file exists: uLinux.conf (we're in the right place) 
skip: autorun.sh already exists: /share/CACHEDEV1_DATA/.system/autorun/autorun.sh 
skip: symlink from partition already exists and points to: /share/CACHEDEV1_DATA/.system/autorun/autorun.sh 
skip: autorun.sh is already enabled in OS 
done: unmounted ubifs autorun partition 
info: your autorun.sh file is located at: /share/CACHEDEV1_DATA/.system/autorun/autorun.sh 
```

Then add my openssh startup script:
```
[~] # cat /share/CACHEDEV1_DATA/.system/autorun/scripts/openssh.sh
# Start OpenSSH
echo "autorun/scripts/openssh.sh: Running"
/opt/etc/init.d/S40sshd start
```

Then reboot.

On boot, openssh is not running:
```
[~] # ps -a | grep ssh
14348 admin      2140 S   /usr/sbin/sshd -f /etc/config/ssh/sshd_config -p 13022 
19495 admin      6064 S   sshd: admin@pts/0                                         
25150 admin       444 S   grep ssh 
```

And the log says **/opt/etc/init.d/S40sshd: No such file or directory**.
```
[~] # cat /var/log/autorun.log
Thu Jan  4 05:41:48 GMT 2024 -- begin processing --
Thu Jan  4 05:41:48 GMT 2024 executing /share/CACHEDEV1_DATA/.system/autorun/scripts/openssh.sh ...
autorun/scripts/openssh.sh: Running
/share/CACHEDEV1_DATA/.system/autorun/scripts/openssh.sh: line 3: /opt/etc/init.d/S40sshd: No such file or directory
Thu Jan  4 05:41:48 GMT 2024 -- end processing --
```

Clearly the Autorun component is working, so I know perhaps it is not your program's issue.

But do you have any insight into how I can troubleshoot this?

I'm quite deep in forum posts from 2010-2023 and can't get anywhere.

Would appreciate any insight if you happen to have the time.

**Comment by OneCDOnly** [comment]
Hi mate. :)

The reason it won’t run is because autorun.sh is executed before the QPKGs have been started. So anything in /opt won’t be there at the time your script is run, if it’s triggered by autorun.sh

Maybe try the RunLast QPKG instead? It’s designed to run user scripts after all installed QPKGs have been started.

**Comment by seb26** [comment]
Thanks for getting back to me so quickly.

I have switched to RunLast and it has launched openssh as intended! (albeit a few mins after the QNAP comes back up - the device must be slow to load everything)

**Comment by H4Z4RD-H42** [comment]
Sorry to write in another user's topic, which is also closed, but I've been trying to complete a project for 2 weeks and I'm stuck because of this SSH problem. I have the same problem and I can't use RunLast because of the NAS FW version (TS-251D). I've tried everything, in manual mode everything works fine, but if I put the same command in a script executed at boot by autorun.sh (thanks to your create-autorun), I always get the error "Key verification failed" (I'm using a key to authenticate without entering the password when I establish the SSH connection to another server, I'm creating a reverse tunnel proxy from the NAS to a remote server, in manual mode it works fine, from the remote server I can see the NAS folders, but with autorun.sh it gives me that error). Could you give me a tip, some advice? I really don't know how to solve it. Thanks!
